### ISSUE TITLE
你好，为什么，代码上面很多红色的还能运行？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [zhijiezhong/crnn#1]
你好，为什么，代码上面很多红色的还能运行？微信nlanguage

![QQ图片20220217232216](https://user-images.githubusercontent.com/41010669/154512993-0a92fc4e-6f79-43a4-b478-9b1ea722f62c.png)

**Comment by zhijiezhong** [comment]
你好，报错可能是pycharm自身原因，我的就没有报错，那里import的是这个目录下的文件，有这些文件肯定可以运行

**Comment by nissansz** [comment]
哦。我mark as source 好像也没用。
690张图，训练2轮，测试结果全是失败，是正常的吗？要怎样才能正确识别？

C:\Users\Ni\AppData\Local\Programs\Python\Python38\python.exe F:/pycharm2020.2/crnn-master/test.py
load weights/chinese_2_82.80496325595773_0.0.pt model success!
device: cpu
test_batch_loss=84.44302188648896, test_batch_acc=0.0
test_loss=84.44302188648896, test_acc=0.0
但是先不说妈妈 ------------>    ❌❌❌
我绝对不想成为爸爸那样的人 ------------>    ❌❌❌
我爸爸逃避着自己的问题 ------------>    ❌❌❌
只替周围的人操心 ------------>    ❌❌❌
有没有我能做的事呢 ------------>    ❌❌❌
我想我一定无法成为那样的人 ------------>    ❌❌❌
但是在这个世界上 ------------>    ❌❌❌
有很多逃避自己问题的人 ------------>    ❌❌❌
这样的人很轻松 ------------>    ❌❌❌

**Comment by zhijiezhong** [comment]
正常，我训练了一天准确率才是96，你现在训练太少了，在训练集的准确率还是0。我训练用的是100万的数据集，训练用lr=0.0001训练的3个epoch，再lr=0.00001训练2个epoch

**Comment by nissansz** [comment]
lr=0.0001  在哪里设置？
您训练的模型可以分享吗？我想测试看看准确率。

**Comment by zhijiezhong** [comment]
模型：https://cloud.189.cn/web/share?code=U7NV3iNbmYvi
数据集：https://cloud.189.cn/web/share?code=eyuiiyjyEFva（访问码：4giq）

**Comment by nissansz** [comment]
谢谢。自己准备的训练用的图片，要不要先用ctpn的定位把它裁边裁成只剩文字的？每张图的尺寸要统一吗？

**Comment by zhijiezhong** [comment]
![image](https://user-images.githubusercontent.com/76642689/154516528-0dc4c9b5-6755-447b-a12a-4b00abcdf0aa.png)
学习率这里设置

**Comment by zhijiezhong** [comment]
需要裁剪成只有文字，但不需要统一尺寸，我会在读取数据集时处理成32*1000的大小。这里的1000你可以改，改源代码

**Comment by nissansz** [comment]
下载了你那个chinese_4_0.4110666987350187_0.95999.pt
我用我自己的图片测试为什么报错？必须要用训练的图片才能有结果？

C:\Users\Ni\AppData\Local\Programs\Python\Python38\python.exe F:/pycharm2020.2/crnn-master/test.py
Traceback (most recent call last):
  File "F:/pycharm2020.2/crnn-master/test.py", line 91, in <module>
    main(opt)
  File "F:/pycharm2020.2/crnn-master/test.py", line 62, in main
    crnn.load_state_dict(torch.load(opt.weights, map_location=torch.device('cpu')))
  File "C:\Users\Ni\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CRNN:
	size mismatch for rnn.1.embedding.weight: copying a param with shape torch.Size([2569, 512]) from checkpoint, the shape in current model is torch.Size([776, 512]).
	size mismatch for rnn.1.embedding.bias: copying a param with shape torch.Size([2569]) from checkpoint, the shape in current model is torch.Size([776]).

**Comment by zhijiezhong** [comment]
你发一张图片让我测试一下

**Comment by nissansz** [comment]
识别时是一定要用二值化图？还是场景文字也可以？
下面有4张图。2张中文，2张日文。
识别时，也要用ctpn裁剪成只剩文字区域？然后二值化，再进行识别？
![0_00_21_016__0_00_22_351_0000000000000000000000001](https://user-images.githubusercontent.com/41010669/154519107-5eee6bbe-fe98-4e95-b11f-4dbd6621f0de.png)
![0_00_21_016__0_00_22_351_0000000000000000000000001](https://user-images.githubusercontent.com/41010669/154519154-5c8b873b-cd1f-4639-9694-309c2efb2c9d.png)


![0_00_21_016__0_00_22_351_0000000000000000000000001](https://user-images.githubusercontent.com/41010669/154519234-0eb2e725-2c92-47e1-9060-12569a60cb9f.png)

![0_00_21_016__0_00_22_351_0000000000000000000000001](https://user-images.githubusercontent.com/41010669/154519218-e4a9bf05-1d69-42c3-b9e8-d83a23832b1b.png)

**Comment by zhijiezhong** [comment]
我在读取图片时就二值化了

**Comment by nissansz** [comment]
> 我在读取图片时就二值化了

但是如果我给的是白底黑字的图，没必要二值化吧？

**Comment by nissansz** [comment]
chinese_7_18.998092761142647_0.0

18.998092761142647 是代表什么？

如果我按默认设置先训练10epochs
然后可以用weights, 继续接着最后生成的pt文件，继续训练？

**Comment by zhijiezhong** [comment]
chinese_7_18.998092761142647_0.0代表的意思是 chinese_epoch_loss_acc。可以加载保存好的权重继续训练

**Comment by zhijiezhong** [comment]
你好，加你微信了，回复一下
